// <auto-generated />
using MVC_App_SPD311.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_App_SPD311.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    partial class FootballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_App_SPD311.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Players")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FootballTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Spain",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
                            Name = "FC Barcelona",
                            Players = 26
                        },
                        new
                        {
                            Id = 2,
                            Country = "Spain",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
                            Name = "Real Madrid",
                            Players = 25
                        },
                        new
                        {
                            Id = 3,
                            Country = "England",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
                            Name = "Manchester United",
                            Players = 24
                        },
                        new
                        {
                            Id = 4,
                            Country = "England",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
                            Name = "Manchester City",
                            Players = 25
                        },
                        new
                        {
                            Id = 5,
                            Country = "England",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
                            Name = "Liverpool",
                            Players = 26
                        },
                        new
                        {
                            Id = 6,
                            Country = "France",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg",
                            Name = "Paris Saint-Germain",
                            Players = 27
                        },
                        new
                        {
                            Id = 7,
                            Country = "Germany",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/c/c5/Bayern_Munich_logo_%282017%29.svg",
                            Name = "Bayern Munich",
                            Players = 25
                        },
                        new
                        {
                            Id = 8,
                            Country = "Germany",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/6/67/Borussia_Dortmund_logo.svg",
                            Name = "Borussia Dortmund",
                            Players = 24
                        },
                        new
                        {
                            Id = 9,
                            Country = "Italy",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/d/d2/Juventus_FC_2017_logo.svg",
                            Name = "Juventus",
                            Players = 26
                        },
                        new
                        {
                            Id = 10,
                            Country = "Italy",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/0/05/Inter_Milan_2021_logo.svg",
                            Name = "Inter Milan",
                            Players = 24
                        },
                        new
                        {
                            Id = 11,
                            Country = "Italy",
                            Logo = "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg",
                            Name = "AC Milan",
                            Players = 25
                        },
                        new
                        {
                            Id = 12,
                            Country = "England",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
                            Name = "Arsenal",
                            Players = 24
                        },
                        new
                        {
                            Id = 13,
                            Country = "England",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg",
                            Name = "Chelsea",
                            Players = 25
                        },
                        new
                        {
                            Id = 14,
                            Country = "Spain",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg",
                            Name = "Atletico Madrid",
                            Players = 24
                        },
                        new
                        {
                            Id = 15,
                            Country = "Italy",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/2/28/SSC_Napoli.svg",
                            Name = "Napoli",
                            Players = 24
                        },
                        new
                        {
                            Id = 16,
                            Country = "Italy",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/0/04/AS_Roma_logo_%282017%29.svg",
                            Name = "AS Roma",
                            Players = 23
                        },
                        new
                        {
                            Id = 17,
                            Country = "England",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg",
                            Name = "Tottenham Hotspur",
                            Players = 24
                        },
                        new
                        {
                            Id = 18,
                            Country = "Spain",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/8/86/Sevilla_FC_logo.svg",
                            Name = "Sevilla",
                            Players = 25
                        },
                        new
                        {
                            Id = 19,
                            Country = "Germany",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/a/a5/RB_Leipzig_2014_logo.svg",
                            Name = "RB Leipzig",
                            Players = 24
                        },
                        new
                        {
                            Id = 20,
                            Country = "Netherlands",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/7/7f/Ajax_Amsterdam.svg",
                            Name = "Ajax",
                            Players = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
